{% set name = "lineapy" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lineapy-{{ version }}.tar.gz
  sha256: d4cf90782426d3c69a114e70675dd88940d11f253966e7e377078cc7b13780d7

build:
  entry_points:
    - lineapy=lineapy.cli.cli:linea_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - asttokens
    - black
    - click >=8.0.0
    - ipython >=7.0.0
    - isort
    - jinja2
    - nbconvert <7.0.0
    - nbformat
    - networkx
    - pydantic
    - python >=3.7
    - pyyaml
    - requests
    - rich
    - sqlalchemy

test:
  imports:
    - lineapy
  commands:
    - pip check
    - lineapy --help
  requires:
    - pip

about:
  home: https://github.com/LineaLabs/lineapy/
  summary: Data engineering, simplified. LineaPy creates a frictionless path for taking your data science artifact from development to production.
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
